### ISSUE TITLE
Vide Version 0.7.1 Doesn't Run On Windows Computers

### ISSUE THREAD

**Issue by Wajinn** [IsaiahPatton/Vide#5]
V version: V 0.2.4 089c93b
OS: Windows 8.1/10

What did you do?

downloaded vide_windows.zip (Vide version 0.7.1)

What did you expect to see?

Running Vide

What did you see instead?

"The application was unable to start correctly"

Comparatively, Vide version 0.0.6 (zip) runs on the Windows 8.1 and 10 computers that I could test on.

**Comment by Wajinn** [comment]
V version: V 0.2.4 089c93b
OS: Windows 8.1

What did you do?

downloaded vide_windows.zip

What did you expect to see?

Running Vide

What did you see instead?

"The application was unable to start correctly"

**Comment by IsaiahPatton** [comment]
It seems I forgot to compile with `-cflags -static`, this download should work:
[vide_windows.zip](https://github.com/IsaiahPatton/Vide/files/8292544/vide_windows.zip)

**Comment by Wajinn** [comment]
Thanks.
